/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author andre
 */
public class Admon extends javax.swing.JFrame {

    /**
     * Creates new form Admon
     */
    public Admon() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        RegProp = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        ModProp = new javax.swing.JButton();
        FactProp = new javax.swing.JButton();
        RegEmp = new javax.swing.JButton();
        ModEmp = new javax.swing.JButton();
        FactEmp = new javax.swing.JButton();
        RegEsp = new javax.swing.JButton();
        ModEsp = new javax.swing.JButton();
        NovEsp = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(227, 181, 102));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Propietario");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Empleado");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Espacios");

        RegProp.setBackground(new java.awt.Color(244, 209, 127));
        RegProp.setForeground(new java.awt.Color(0, 0, 0));
        RegProp.setText("Registro");
        RegProp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegPropActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(244, 209, 127));
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Multas");

        ModProp.setBackground(new java.awt.Color(244, 209, 127));
        ModProp.setForeground(new java.awt.Color(0, 0, 0));
        ModProp.setText("Modificar");
        ModProp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModPropActionPerformed(evt);
            }
        });

        FactProp.setBackground(new java.awt.Color(244, 209, 127));
        FactProp.setForeground(new java.awt.Color(0, 0, 0));
        FactProp.setText("Facturación");

        RegEmp.setBackground(new java.awt.Color(244, 209, 127));
        RegEmp.setForeground(new java.awt.Color(0, 0, 0));
        RegEmp.setText("Registro");
        RegEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegEmpActionPerformed(evt);
            }
        });

        ModEmp.setBackground(new java.awt.Color(244, 209, 127));
        ModEmp.setForeground(new java.awt.Color(0, 0, 0));
        ModEmp.setText("Modificar");

        FactEmp.setBackground(new java.awt.Color(244, 209, 127));
        FactEmp.setForeground(new java.awt.Color(0, 0, 0));
        FactEmp.setText("Facturación");

        RegEsp.setBackground(new java.awt.Color(244, 209, 127));
        RegEsp.setForeground(new java.awt.Color(0, 0, 0));
        RegEsp.setText("Registro");
        RegEsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegEspActionPerformed(evt);
            }
        });

        ModEsp.setBackground(new java.awt.Color(244, 209, 127));
        ModEsp.setForeground(new java.awt.Color(0, 0, 0));
        ModEsp.setText("Modificar");

        NovEsp.setBackground(new java.awt.Color(244, 209, 127));
        NovEsp.setForeground(new java.awt.Color(0, 0, 0));
        NovEsp.setText("Novedades");

        jLabel4.setText("Imagen");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(RegEmp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ModEmp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FactEmp)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(RegEsp)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ModEsp)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(NovEsp))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(RegProp)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ModProp)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(FactProp))))))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegProp)
                    .addComponent(jButton2)
                    .addComponent(ModProp)
                    .addComponent(FactProp))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegEmp)
                    .addComponent(ModEmp)
                    .addComponent(FactEmp))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegEsp)
                    .addComponent(NovEsp)
                    .addComponent(ModEsp))
                .addContainerGap(141, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegPropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegPropActionPerformed
        // TODO add your handling code here:
        NuevoRegistroProp nuvProp = new NuevoRegistroProp();
        nuvProp.setVisible(true);
    }//GEN-LAST:event_RegPropActionPerformed

    private void RegEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegEmpActionPerformed

    private void RegEspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegEspActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegEspActionPerformed

    private void ModPropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModPropActionPerformed
        // TODO add your handling code here:
        ActualizarPropietario actProp = new ActualizarPropietario();
        actProp.setVisible(true);
    }//GEN-LAST:event_ModPropActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FactEmp;
    private javax.swing.JButton FactProp;
    private javax.swing.JButton ModEmp;
    private javax.swing.JButton ModEsp;
    private javax.swing.JButton ModProp;
    private javax.swing.JButton NovEsp;
    private javax.swing.JButton RegEmp;
    private javax.swing.JButton RegEsp;
    private javax.swing.JButton RegProp;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
